site_name: Shopping Store
site_author: "Justin-Anthony Joco"

copyright:   'Copyright &copy; 2024 Justin-Anthony Joco'


theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences